### PR TITLE
Makefile: Add build and run targets

### PR DESCRIPTION
**Pull request by gggiii**
A couple improvements to the makefile:

- Explicitly set shell as bash (throws errors on WSL2)
- Add `build` and `run` targets to be able to compile and run the project on its own.

### CODE REVIEW

**Comment by alessiogambi** [comment]
@gggiii Thanks for the PR. I did not see it and committed a few updates that fixe the shell setup.

let me take a look at the building part because there might be some redundancy

**Comment by gggiii** [comment]
@alessiogambi I though the the project will have just a single entrypoint (Main.c) where the contents would look something like 
`
int main(){
   take user input if client or server should run
   if(server should run){
      // get additional input for server
     // run server
   }else{
      // get additional input for client
     // run client
    }
}
`
so a single entrypoint spawns the processes. In this case the run target makes sense. If client and server should be separate binaries that run then we need separate run targets or just run them directly.

As you said, I made the build targets separate just so they run the project in a minimal setup (wthout coverage)

**Comment by alessiogambi** [comment]
Ok. In this case, the main.c should also be updates with a skeleton code or
a comment about this strategy.

**Comment by gggiii** [comment]
Unfortunately I cannot update the Main.c file since it comes from the Classroom template, so here's the contents
```c
#include <stdio.h>
#include "Calc.h"

int main(int argc, char *argv[])
{
    //
    // Placeholder code to test building
    // 
    printf("'10 + 2 = %d'\n", add(10, 2));
    printf("'10 - 2 = %d'\n", sub(10, 2));
    printf("'10 * 2 = %d'\n", mul(10, 2));
    printf("'10 / 2 = %d'\n", div(10, 2));
    printf("'10 % 2 = %d'\n", mod(10, 2));
    printf("'10 power two = %d'\n", power_two(10));
    printf("'10 power three = %d'\n", power(10, 3));

    int arr[10];
    size_t size = sizeof(arr) / sizeof(arr[0]);
    fill_single_digit_positive_number(arr, size);


    //
    // Base skeleton
    //

    int run_server;
    // Take user input if client or server should run
    if (run_server == 1) {
      // Get additional user input for server
      // Run server
    } else {
      // Get additional user input for client
      // Run client
    }

    return 0;
}

```

**Comment by alessiogambi** [comment]
> Unfortunately I cannot update the Main.c file since it comes from the Classroom template, so here's the contents
> 
> ```c
> #include <stdio.h>
> #include "Calc.h"
> 
> int main(int argc, char *argv[])
> {
>     //
>     // Placeholder code to test building
>     // 
>     printf("'10 + 2 = %d'\n", add(10, 2));
>     printf("'10 - 2 = %d'\n", sub(10, 2));
>     printf("'10 * 2 = %d'\n", mul(10, 2));
>     printf("'10 / 2 = %d'\n", div(10, 2));
>     printf("'10 % 2 = %d'\n", mod(10, 2));
>     printf("'10 power two = %d'\n", power_two(10));
>     printf("'10 power three = %d'\n", power(10, 3));
> 
>     int arr[10];
>     size_t size = sizeof(arr) / sizeof(arr[0]);
>     fill_single_digit_positive_number(arr, size);
> 
> 
>     //
>     // Base skeleton
>     //
> 
>     int run_server;
>     // Take user input if client or server should run
>     if (run_server == 1) {
>       // Get additional user input for server
>       // Run server
>     } else {
>       // Get additional user input for client
>       // Run client
>     }
> 
>     return 0;
> }
> ```

Actually, this is not necessary. I mean, every student will implement main as they like knowing that the command will receive the `--server` or `--client` argument

**Comment by gggiii** [comment]
@alessiogambi fixed all the points you mentioned

**Pull request merged**
