### PR TITLE
Define the user interface for the assignment

### LINKED ISSUE #5: Define the user interface for the assignment
The assignment description should contain a precise definition of the UI of the system

### PR DESCRIPTION
**Pull request by alessiogambi**
This pull request proposes the UI of the system and main interactions/use cases for client.

### CODE REVIEW

**Comment by michaelpoi** [comment]
For me it`s not clear that Play the game and Join the game are different options. Maybe it could be nice to change Play the game to "Current games" or something like that.

**Comment by gggiii** [comment]
Question: we assume that `Enter`  (\n) is to be pressed after each input, right? So the file that you will pipe into the program to test it will have each command on a new line rather than a sequence of characters in one line?

**Comment by andrewjcraig** [comment]
Is it defined that players can join mid-game, or must they join prior to commencement of round 1?

Is there a timer between rounds? Would one player hold the game indefinitely by not submitting a play?

**Comment by alessiogambi** [comment]
> For me it`s not clear that Play the game and Join the game are different options. Maybe it could be nice to change Play the game to "Current games" or something like that.

Ok. In this case, we change to "Current games" that lists the (active) game the user is playing and "Waiting room" the games that the user can join and play (so games that are waiting for players)

**Comment by alessiogambi** [comment]
> Question: we assume that `Enter` (\n) is to be pressed after each input, right? So the file that you will pipe into the program to test it will have each command on a new line rather than a sequence of characters in one line?

Correct. The test inputs will look like `1\n1\nb\n`

**Comment by alessiogambi** [comment]
> ~Is it defined that players can join mid-game, or must they join prior to commencement of round 1?~ No of players defined at creation, so presumably if players cannot leave and game cannot start before n players reached.
> 
> Is there a timer between rounds? Would one player hold the game indefinitely by not submitting a play?

No timer. Games can indefinitely wait for players to join and to submit gestures/actions. Once the server shuts down, all the information (including the leaderboard) will be lost.

**Pull request merged**
